[context]
name = "trait-aliases"
version = "0.2.0"
url = "https://github.com/nekitdev/trait-aliases"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
